export const SEED_ARTWORKS = [
  {
    id: 'seed-1',
    title: 'Amber Reverie',
    artist: 'Isabella Moreau',
    category: 'Paintings',
    description:
      'An oil-on-canvas study of warm light falling across a quiet interior, built up in loose, confident strokes.',
    year: 2022,
    price: 4200,
    availability: 'available',
    featured: true,
    enabled: true,
    tags: ['oil', 'interior', 'warm-tones'],
    images: ['https://images.unsplash.com/photo-1549289524-06cf8837ace5?q=80&w=1200'],
    resources: [],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: 'seed-2',
    title: 'Fractured Signal',
    artist: 'Kenji Okafor',
    category: 'Digital Art',
    description:
      'A generative composition exploring noise and order, rendered as a limited-edition archival print.',
    year: 2023,
    price: 1800,
    availability: 'available',
    featured: true,
    enabled: true,
    tags: ['generative', 'print', 'abstract'],
    images: ['https://images.unsplash.com/photo-1633186710895-309db2eca9e4?q=80&w=1200'],
    resources: [],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
  {
    id: 'seed-3',
    title: 'Silence in Grey',
    artist: 'Nadia Petrov',
    category: 'Photography',
    description:
      'A monochrome silver-gelatin print capturing an empty stairwell at dawn, printed on museum-grade paper.',
    year: 2021,
    price: 950,
    availability: 'available',
    featured: false,
    enabled: true,
    tags: ['monochrome', 'architecture', 'fine-art'],
    images: ['https://images.unsplash.com/photo-1554907984-15263bfd63bd?q=80&w=1200'],
    resources: [],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 9,
  },
  {
    id: 'seed-4',
    title: 'Bronze Sentinel',
    artist: 'Marcus Webb',
    category: 'Sculptures',
    description:
      'A cast bronze figure finished in a hand-applied patina, standing just over four feet tall.',
    year: 2020,
    price: 12500,
    availability: 'reserved',
    featured: true,
    enabled: true,
    tags: ['bronze', 'figurative', 'patina'],
    images: ['https://images.unsplash.com/photo-1608599947359-6c0e97d3aa7c?q=80&w=1200'],
    resources: [],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 20,
  },
  {
    id: 'seed-5',
    title: 'Verdant Hour',
    artist: 'Isabella Moreau',
    category: 'Paintings',
    description: 'A large-format acrylic piece built from layered greens and gold leaf accents.',
    year: 2023,
    price: 5600,
    availability: 'available',
    featured: false,
    enabled: true,
    tags: ['acrylic', 'gold-leaf', 'landscape'],
    images: ['https://images.unsplash.com/photo-1502691876148-a84978e59af8?q=80&w=1200'],
    resources: [],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 12,
  },
  {
    id: 'seed-6',
    title: 'Glass Horizon',
    artist: 'Kenji Okafor',
    category: 'Digital Art',
    description: 'A minimal gradient study exploring the boundary between sky and sea.',
    year: 2024,
    price: 1200,
    availability: 'available',
    featured: false,
    enabled: true,
    tags: ['gradient', 'minimal', 'print'],
    images: ['https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=1200'],
    resources: [],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
  },
  {
    id: 'seed-7',
    title: 'Marble Whisper',
    artist: 'Marcus Webb',
    category: 'Sculptures',
    description: 'A hand-carved Carrara marble bust exploring quiet, introspective expression.',
    year: 2019,
    price: 18900,
    availability: 'sold',
    featured: false,
    enabled: true,
    tags: ['marble', 'carved', 'classical'],
    images: ['https://images.unsplash.com/photo-1608278047522-58806a6ac85f?q=80&w=1200'],
    resources: [],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
  },
  {
    id: 'seed-8',
    title: 'Departure Platform',
    artist: 'Nadia Petrov',
    category: 'Photography',
    description: 'A long-exposure black-and-white print of a night train station, framed in oak.',
    year: 2022,
    price: 1100,
    availability: 'available',
    featured: true,
    enabled: true,
    tags: ['long-exposure', 'monochrome', 'travel'],
    images: ['https://images.unsplash.com/photo-1495563780331-a0a03e5bcd83?q=80&w=1200'],
    resources: [],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 15,
  },
];
